name: CI - Vérification HTML

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-html:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Vérification de index.html
        uses: Cyb3r-Jak3/html5validator-action@v0.6
        with:
          root: .
          files: index.html
