name: CI/CD LAMP

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    env:
      WP_DB_USER: user
      WP_DB_NAME: wordpress
      WP_DB_HOST: db:3306
      DOCKER_IMAGE: blackshadow20/icrc:latest

    steps:
      - name: Vérification du code
        uses: actions/checkout@v4

      - name: Générer un mot de passe aléatoire
        id: gen-pass
        run: |
          PASS=$(openssl rand -hex 12)
          echo "WP_DB_PASSWORD=$PASS" >> $GITHUB_ENV
          echo "Mot de passe généré : $PASS"

      - name: Configuration Docker
        run: |
          docker --version
          docker compose version || true

- name: Configure docker-compose.yml
  run: |
    cat > docker-compose.yml <<EOF
version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: $WP_DB_NAME
      MYSQL_USER: $WP_DB_USER
      MYSQL_PASSWORD: $WP_DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $WP_DB_PASSWORD
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5

  wordpress:
    image: wordpress:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $WP_DB_USER
      WORDPRESS_DB_PASSWORD: $WP_DB_PASSWORD
      WORDPRESS_DB_NAME: $WP_DB_NAME

  adminer:
    image: adminer
    ports:
      - "8081:8080"
EOF

