name: Déploiement sous Nginx v4

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files with SCP (to home dir)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./"
          target: "/home/${{ secrets.SSH_USER }}/app"

      - name: Setup Nginx and deploy files
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if ! command -v nginx >/dev/null 2>&1; then
              sudo apt update -y
              sudo apt install -y nginx
            fi

            # move files from home dir to /var/www/app
            sudo mkdir -p /var/www/app
            sudo cp -r /home/${USER}/app/* /var/www/app/
            sudo chown -R www-data:www-data /var/www/app

            sudo tee /etc/nginx/sites-available/app > /dev/null <<EOF
            server {
              listen 80;
              server_name _;
              root /var/www/app;
              index index.html;

              location / {
                try_files \$uri \$uri/ =404;
              }
            }
            EOF

            sudo ln -sf /etc/nginx/sites-available/app /etc/nginx/sites-enabled/app
            sudo nginx -t
            sudo systemctl restart nginx
