name: Déploiement sous Nginx v4

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Préparer le dossier cible
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo mkdir -p /var/www/app
            sudo chown -R $USER:$USER /var/www/app

      - name: Copier les fichiers avec SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./dist"    # ajuste selon ton dossier de build
          target: "/var/www/app"

      - name: Installer et configurer Nginx
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if ! command -v nginx >/dev/null 2>&1; then
              sudo apt update -y
              sudo apt install -y nginx
            fi

            tee /tmp/app_nginx_conf > /dev/null <<EOF
            server {
              listen 80;
              server_name _;
              root /var/www/app;
              index index.html;

              location / {
                try_files \$uri \$uri/ =404;
              }
            }
            EOF

            sudo mv /tmp/app_nginx_conf /etc/nginx/sites-available/app
            sudo ln -sf /etc/nginx/sites-available/app /etc/nginx/sites-enabled/app
            sudo nginx -t
            sudo systemctl restart nginx
